import os
import sys
import re
import json
from dotenv import load_dotenv
from langchain_groq import ChatGroq
load_dotenv()

def extract_json(text):
    """Extract JSON from LLM response that may contain markdown fences or extra text."""
    text = text.strip()
    text = re.sub(r'^```(?:json)?\s*', '', text)
    text = re.sub(r'\s*```$', '', text)
    text = text.strip()
    try:
        return json.loads(text)
    except json.JSONDecodeError:
        match = re.search(r'\{[\s\S]*\}', text)
        if match:
            return json.loads(match.group())
        raise

def verifier(problem_text,answer,topic):
    llm = ChatGroq(
        model="llama-3.3-70b-versatile",
        api_key=os.getenv("GROQ_API_KEY"),
        temperature=0.3
    )
    prompt = f"""You are a JEE math verifier.
    You are given a problem and an answer generated by another AI.
    Your job is to re-solve the problem independently and verify if the given answer is correct.

    Topic: {topic}
    Problem: {problem_text}
    Given Answer: {answer}

    Re-solve this problem step by step, then compare your answer with the given answer.

    Return ONLY this JSON:
    {{
        "verdict": "correct or incorrect or partially_correct",
        "correct_answer": "your computed answer",
        "explanation": "why it is correct or wrong",
        "confidence": 0.9
    }}"""
    response = llm.invoke(prompt)
    result = extract_json(response.content)
    if result["verdict"] == "incorrect":
        print(" HITL: Answer is incorrect! Needs human review.")
    if result["confidence"] < 0.7:
        print("HITL: Low confidence!")

    return result



